{
  "Yeezy Pirate Bred ": {
    "Name of item": "Yeezy Pirate Bred ",
    "Color": "Black",
    "Item Type": "Shoes",
    "Size": "13",
    "Brand": "Adidas",
    "My Cost": 239.8,
    "Gross sale": 680,
    "Comission": 98.95,
    "Gross minus comish": 581.05,
    "Net Profit $": 341.24999999999994,
    "Net Profit %": 1.423060884070058
  },
  "Yeezy Cream": {
    "Name of item": "Yeezy Cream",
    "Color": "White",
    "Item Type": "Shoes",
    "Size": "11",
    "Brand": "Adidas",
    "My Cost": 239.8,
    "Gross sale": 475,
    "Comission": 59.37,
    "Gross minus comish": 415.63,
    "Net Profit $": 175.82999999999998,
    "Net Profit %": 0.7332360300250208
  },
  "Yeezy Cream ": {
    "Name of item": "Yeezy Cream ",
    "Color": "White",
    "Item Type": "Shoes",
    "Size": "9.5",
    "Brand": "Adidas",
    "My Cost": 239.8,
    "Gross sale": 475,
    "Comission": 59.37,
    "Gross minus comish": 415.63,
    "Net Profit $": 175.82999999999998,
    "Net Profit %": 0.7332360300250208
  },
  "Supreme cap new era 5 panel": {
    "Name of item": "Supreme cap new era 5 panel",
    "Color": "Blue",
    "Item Type": "Hat",
    "Size": "OS",
    "Brand": "Supreme",
    "My Cost": 52.32,
    "Gross sale": 80,
    "Comission": 12,
    "Gross minus comish": 68,
    "Net Profit $": 15.68,
    "Net Profit %": 0.2996941896024465
  },
  "Palace Skeledon LS": {
    "Name of item": "Palace Skeledon LS",
    "Color": "White",
    "Item Type": "Long Sleeve Shirt",
    "Size": "XL",
    "Brand": "Palace",
    "My Cost": 70,
    "Gross sale": 125,
    "Comission": 18.75,
    "Gross minus comish": 106.25,
    "Net Profit $": 36.25,
    "Net Profit %": 0.5178571428571429
  },
  "Palace Skeledon Hood": {
    "Name of item": "Palace Skeledon Hood",
    "Color": "White",
    "Item Type": "Sweatshirt",
    "Size": "XL",
    "Brand": "Palace",
    "My Cost": 160,
    "Gross sale": 270,
    "Comission": 40.5,
    "Gross minus comish": 229.5,
    "Net Profit $": 69.5,
    "Net Profit %": 0.434375
  },
  "Supreme Escher Sphere tee": {
    "Name of item": "Supreme Escher Sphere tee",
    "Color": "Grey",
    "Item Type": "T Shirt",
    "Size": "L",
    "Brand": "Supreme",
    "My Cost": 48.72,
    "Gross sale": 115,
    "Comission": 17.25,
    "Gross minus comish": 97.75,
    "Net Profit $": 49.03,
    "Net Profit %": 1.0063628899835797
  },
  "Supreme Seersucker camp": {
    "Name of item": "Supreme Seersucker camp",
    "Color": "Red",
    "Item Type": "Hat",
    "Size": "OS",
    "Brand": "Supreme",
    "My Cost": 48.72,
    "Gross sale": 105,
    "Comission": 0,
    "Gross minus comish": 105,
    "Net Profit $": 56.28,
    "Net Profit %": 1.1551724137931034
  },
  "Supreme Champion cap": {
    "Name of item": "Supreme Champion cap",
    "Color": "Red",
    "Item Type": "Hat",
    "Size": "OS",
    "Brand": "Supreme",
    "My Cost": 53.08,
    "Gross sale": 100,
    "Comission": 15,
    "Gross minus comish": 85,
    "Net Profit $": 31.92,
    "Net Profit %": 0.6013564431047476
  },
  "Supreme curve logo tee": {
    "Name of item": "Supreme curve logo tee",
    "Color": "Grey",
    "Item Type": "Hat",
    "Size": "L",
    "Brand": "Supreme",
    "My Cost": 79.13,
    "Gross sale": 115,
    "Comission": 17.25,
    "Gross minus comish": 97.75,
    "Net Profit $": 18.620000000000005,
    "Net Profit %": 0.23530898521420454
  },
  "Palace 3d tee": {
    "Name of item": "Palace 3d tee",
    "Color": "White",
    "Item Type": "T Shirt",
    "Size": "L",
    "Brand": "Palace",
    "My Cost": 60,
    "Gross sale": 150,
    "Comission": 22.5,
    "Gross minus comish": 127.5,
    "Net Profit $": 67.5,
    "Net Profit %": 1.125
  },
  "Supreme GFY Pocket Tee ": {
    "Name of item": "Supreme GFY Pocket Tee ",
    "Color": "Red",
    "Item Type": "T Shirt",
    "Size": "L",
    "Brand": "Supreme",
    "My Cost": 49,
    "Gross sale": 115,
    "Comission": 17.25,
    "Gross minus comish": 97.75,
    "Net Profit $": 48.75,
    "Net Profit %": 0.9948979591836735
  },
  "Supreme Buy off the Bar Tee ": {
    "Name of item": "Supreme Buy off the Bar Tee ",
    "Color": "Red",
    "Item Type": "T Shirt",
    "Size": "L",
    "Brand": "Supreme",
    "My Cost": 53.5,
    "Gross sale": 100,
    "Comission": 15,
    "Gross minus comish": 85,
    "Net Profit $": 31.5,
    "Net Profit %": 0.5887850467289719
  },
  "Supreme Digi Tee ": {
    "Name of item": "Supreme Digi Tee ",
    "Color": "Blue",
    "Item Type": "T Shirt",
    "Size": "L",
    "Brand": "Supreme",
    "My Cost": 42.5,
    "Gross sale": 115,
    "Comission": 17.25,
    "Gross minus comish": 97.75,
    "Net Profit $": 55.25,
    "Net Profit %": 1.3
  },
  "Supreme Orgy Tee ": {
    "Name of item": "Supreme Orgy Tee ",
    "Color": "Black",
    "Item Type": "T Shirt",
    "Size": "L",
    "Brand": "Supreme",
    "My Cost": 42.5,
    "Gross sale": 115,
    "Comission": 17.25,
    "Gross minus comish": 97.75,
    "Net Profit $": 55.25,
    "Net Profit %": 1.3
  },
  "Palace ripstop Cap ": {
    "Name of item": "Palace ripstop Cap ",
    "Color": "Blue",
    "Item Type": "Hat",
    "Size": "L",
    "Brand": "Palace",
    "My Cost": 60,
    "Gross sale": 120,
    "Comission": 18,
    "Gross minus comish": 102,
    "Net Profit $": 42,
    "Net Profit %": 0.7
  },
  "Kith X Coca Cola Enjoy LS White": {
    "Name of item": "Kith X Coca Cola Enjoy LS White",
    "Color": "White",
    "Item Type": "Long Sleeve Shirt",
    "Size": "L",
    "Brand": "KITH",
    "My Cost": 75,
    "Gross sale": 140,
    "Comission": 21,
    "Gross minus comish": 119,
    "Net Profit $": 44,
    "Net Profit %": 0.5866666666666667
  },
  "Kith X Coca Cola Enjoy LS Red": {
    "Name of item": "Kith X Coca Cola Enjoy LS Red",
    "Color": "Red",
    "Item Type": "Long Sleeve Shirt",
    "Size": "L",
    "Brand": "KITH",
    "My Cost": 75,
    "Gross sale": 150,
    "Comission": 22.5,
    "Gross minus comish": 127.5,
    "Net Profit $": 52.5,
    "Net Profit %": 0.7
  },
  "KITH X Coca Cola Towel Red": {
    "Name of item": "KITH X Coca Cola Towel Red",
    "Color": "Red",
    "Item Type": "Accessory",
    "Size": "L",
    "Brand": "KITH",
    "My Cost": 75,
    "Gross sale": 120,
    "Comission": 0,
    "Gross minus comish": 120,
    "Net Profit $": 45,
    "Net Profit %": 0.6
  },
  "Kith X Coca Cola Enjoy Red Shirt": {
    "Name of item": "Kith X Coca Cola Enjoy Red Shirt",
    "Color": "Red",
    "Item Type": "T Shirt",
    "Size": "L",
    "Brand": "KITH",
    "My Cost": 70,
    "Gross sale": 140,
    "Comission": 21,
    "Gross minus comish": 119,
    "Net Profit $": 49,
    "Net Profit %": 0.7
  },
  "Kith Classic Logo Tee ": {
    "Name of item": "Kith Classic Logo Tee ",
    "Color": "Grey",
    "Item Type": "T Shirt",
    "Size": "XXL",
    "Brand": "KITH",
    "My Cost": 65,
    "Gross sale": 100,
    "Comission": 15,
    "Gross minus comish": 85,
    "Net Profit $": 20,
    "Net Profit %": 0.3076923076923077
  },
  "P 6-panel Red": {
    "Name of item": "P 6-panel Red",
    "Color": "Red",
    "Item Type": "Hat",
    "Size": "OS",
    "Brand": "Palace",
    "My Cost": 60,
    "Gross sale": 140,
    "Comission": 21,
    "Gross minus comish": 119,
    "Net Profit $": 59,
    "Net Profit %": 0.9833333333333333
  },
  "Supreme Dollar Tee": {
    "Name of item": "Supreme Dollar Tee",
    "Color": "Red",
    "Item Type": "T Shirt",
    "Size": "L",
    "Brand": "Supreme",
    "My Cost": 48,
    "Gross sale": 95,
    "Comission": 0,
    "Gross minus comish": 95,
    "Net Profit $": 47,
    "Net Profit %": 0.9791666666666666
  },
  "NYCO Camp Cap ": {
    "Name of item": "NYCO Camp Cap ",
    "Color": "Camo",
    "Item Type": "Hat",
    "Size": "OS",
    "Brand": "Supreme",
    "My Cost": 63,
    "Gross sale": 130,
    "Comission": 26,
    "Gross minus comish": 104,
    "Net Profit $": 41,
    "Net Profit %": 0.6507936507936508
  },
  "Venus Tee ": {
    "Name of item": "Venus Tee ",
    "Color": "Red",
    "Item Type": "T Shirt",
    "Size": "L",
    "Brand": "Supreme",
    "My Cost": 48,
    "Gross sale": 100,
    "Comission": 20,
    "Gross minus comish": 80,
    "Net Profit $": 32,
    "Net Profit %": 0.6666666666666666
  },
  "Gonz Heads Tee ": {
    "Name of item": "Gonz Heads Tee ",
    "Color": "Red",
    "Item Type": "T Shirt",
    "Size": "L",
    "Brand": "Supreme",
    "My Cost": 58,
    "Gross sale": 120,
    "Comission": 24,
    "Gross minus comish": 96,
    "Net Profit $": 38,
    "Net Profit %": 0.6551724137931034
  },
  "DNA Tee": {
    "Name of item": "DNA Tee",
    "Color": "Red",
    "Item Type": "T Shirt",
    "Size": "S",
    "Brand": "Supreme",
    "My Cost": 48,
    "Gross sale": 115,
    "Comission": 23,
    "Gross minus comish": 92,
    "Net Profit $": 44,
    "Net Profit %": 0.9166666666666666
  },
  "Overdyed Ripstop Camp Cap ": {
    "Name of item": "Overdyed Ripstop Camp Cap ",
    "Color": "Peach",
    "Item Type": "Hat",
    "Size": "OS",
    "Brand": "Supreme",
    "My Cost": 63,
    "Gross sale": 125,
    "Comission": 25,
    "Gross minus comish": 100,
    "Net Profit $": 37,
    "Net Profit %": 0.5873015873015873
  },
  "Loose Gauge Beanie ": {
    "Name of item": "Loose Gauge Beanie ",
    "Color": "Red",
    "Item Type": "Beanie",
    "Size": "OS",
    "Brand": "Supreme",
    "My Cost": 45,
    "Gross sale": 85,
    "Comission": 17,
    "Gross minus comish": 68,
    "Net Profit $": 23,
    "Net Profit %": 0.5111111111111111
  },
  "Supreme Mini Magnetic Flashlight": {
    "Name of item": "Supreme Mini Magnetic Flashlight",
    "Color": "Red",
    "Item Type": "Accessory",
    "Size": "N/A",
    "Brand": "Supreme",
    "My Cost": 63,
    "Gross sale": 100,
    "Comission": 20,
    "Gross minus comish": 80,
    "Net Profit $": 17,
    "Net Profit %": 0.2698412698412698
  },
  "Washed Chino Camp Cap Camo": {
    "Name of item": "Washed Chino Camp Cap Camo",
    "Color": "Camo",
    "Item Type": "Hat",
    "Size": "OS",
    "Brand": "Supreme",
    "My Cost": 70,
    "Gross sale": 140,
    "Comission": 28,
    "Gross minus comish": 112,
    "Net Profit $": 42,
    "Net Profit %": 0.6
  },
  "Tri Flec LS": {
    "Name of item": "Tri Flec LS",
    "Color": "Green",
    "Item Type": "Long Sleeve Shirt",
    "Size": "L",
    "Brand": "Palace",
    "My Cost": 70,
    "Gross sale": 120,
    "Comission": 24,
    "Gross minus comish": 96,
    "Net Profit $": 26,
    "Net Profit %": 0.37142857142857144
  },
  "P Cap Poplin ": {
    "Name of item": "P Cap Poplin ",
    "Color": "Black",
    "Item Type": "Hat",
    "Size": "OS",
    "Brand": "Palace",
    "My Cost": 60,
    "Gross sale": 120,
    "Comission": 24,
    "Gross minus comish": 96,
    "Net Profit $": 36,
    "Net Profit %": 0.6
  },
  "Undefeated X nike air max 97 white": {
    "Name of item": "Undefeated X nike air max 97 white",
    "Color": "White",
    "Item Type": "Shoes",
    "Size": "13",
    "Brand": "Undefeated ",
    "My Cost": 205,
    "Gross sale": 300,
    "Comission": 0,
    "Gross minus comish": 300,
    "Net Profit $": 95,
    "Net Profit %": 0.4634146341463415
  },
  "Undefetaed X nike air max 97 black": {
    "Name of item": "Undefetaed X nike air max 97 black",
    "Color": "Black",
    "Item Type": "Shoes",
    "Size": "8",
    "Brand": "Undefeated ",
    "My Cost": 205,
    "Gross sale": 315,
    "Comission": 63,
    "Gross minus comish": 252,
    "Net Profit $": 47,
    "Net Profit %": 0.22926829268292684
  },
  "Palace deck": {
    "Name of item": "Palace deck",
    "Color": "Black",
    "Item Type": "Deck",
    "Size": "N/A",
    "Brand": "Palace",
    "My Cost": 65,
    "Gross sale": 100,
    "Comission": 0,
    "Gross minus comish": 100,
    "Net Profit $": 35,
    "Net Profit %": 0.5384615384615384
  },
  "Supreme deck": {
    "Name of item": "Supreme deck",
    "Color": "White",
    "Item Type": "Deck",
    "Size": "N/A",
    "Brand": "Supreme",
    "My Cost": 65,
    "Gross sale": 100,
    "Comission": 0,
    "Gross minus comish": 100,
    "Net Profit $": 35,
    "Net Profit %": 0.5384615384615384
  },
  "Biggie Deck": {
    "Name of item": "Biggie Deck",
    "Color": "Black",
    "Item Type": "Deck",
    "Size": "N/A",
    "Brand": "Primative",
    "My Cost": 50,
    "Gross sale": 100,
    "Comission": 0,
    "Gross minus comish": 100,
    "Net Profit $": 50,
    "Net Profit %": 1
  },
  "Plant tee ": {
    "Name of item": "Plant tee ",
    "Color": "Red",
    "Item Type": "T Shirt",
    "Size": "L",
    "Brand": "Supreme",
    "My Cost": 48,
    "Gross sale": 75,
    "Comission": 15,
    "Gross minus comish": 60,
    "Net Profit $": 12,
    "Net Profit %": 0.25
  },
  "Candle tee": {
    "Name of item": "Candle tee",
    "Color": "White",
    "Item Type": "T Shirt",
    "Size": "L",
    "Brand": "Supreme",
    "My Cost": 48,
    "Gross sale": 100,
    "Comission": 20,
    "Gross minus comish": 80,
    "Net Profit $": 32,
    "Net Profit %": 0.6666666666666666
  },
  "Palace Black Getting Higher Shirt ": {
    "Name of item": "Palace Black Getting Higher Shirt ",
    "Color": "White",
    "Item Type": "T Shirt",
    "Size": "L",
    "Brand": "Palace",
    "My Cost": 60,
    "Gross sale": 140,
    "Comission": 28,
    "Gross minus comish": 112,
    "Net Profit $": 52,
    "Net Profit %": 0.8666666666666667
  },
  "Palace Grey Getting Higher Shirt": {
    "Name of item": "Palace Grey Getting Higher Shirt",
    "Color": "Grey",
    "Item Type": "T Shirt",
    "Size": "XL",
    "Brand": "Palace",
    "My Cost": 60,
    "Gross sale": 120,
    "Comission": 24,
    "Gross minus comish": 96,
    "Net Profit $": 36,
    "Net Profit %": 0.6
  },
  "Supreme Akira Arm Tee ": {
    "Name of item": "Supreme Akira Arm Tee ",
    "Color": "White",
    "Item Type": "T Shirt",
    "Size": "L",
    "Brand": "Supreme",
    "My Cost": 63,
    "Gross sale": 115,
    "Comission": 23,
    "Gross minus comish": 92,
    "Net Profit $": 29,
    "Net Profit %": 0.4603174603174603
  },
  "Supreme Neo Tokyo LS tee ": {
    "Name of item": "Supreme Neo Tokyo LS tee ",
    "Color": "Black",
    "Item Type": "Long Sleeve Shirt",
    "Size": "L",
    "Brand": "Supreme",
    "My Cost": 74,
    "Gross sale": 140,
    "Comission": 28,
    "Gross minus comish": 112,
    "Net Profit $": 38,
    "Net Profit %": 0.5135135135135135
  },
  "P-3D LONGSLEEVE FLURO ": {
    "Name of item": "P-3D LONGSLEEVE FLURO ",
    "Color": "Yellow",
    "Item Type": "Long Sleeve Shirt",
    "Size": "L",
    "Brand": "Palace",
    "My Cost": 70,
    "Gross sale": 125,
    "Comission": 25,
    "Gross minus comish": 100,
    "Net Profit $": 30,
    "Net Profit %": 0.42857142857142855
  },
  "P-3D LONGSLEEVE BLACK ": {
    "Name of item": "P-3D LONGSLEEVE BLACK ",
    "Color": "Black",
    "Item Type": "Long Sleeve Shirt",
    "Size": "L",
    "Brand": "Palace",
    "My Cost": 70,
    "Gross sale": 140,
    "Comission": 28,
    "Gross minus comish": 112,
    "Net Profit $": 42,
    "Net Profit %": 0.6
  },
  "P-3D LONGSLEEVE WHITE ": {
    "Name of item": "P-3D LONGSLEEVE WHITE ",
    "Color": "White",
    "Item Type": "Long Sleeve Shirt",
    "Size": "L",
    "Brand": "Palace",
    "My Cost": 70,
    "Gross sale": 140,
    "Comission": 28,
    "Gross minus comish": 112,
    "Net Profit $": 42,
    "Net Profit %": 0.6
  },
  "Shoulder Bag Black": {
    "Name of item": "Shoulder Bag Black",
    "Color": "Black",
    "Item Type": "Accessory",
    "Size": "OS",
    "Brand": "Supreme",
    "My Cost": 84.1,
    "Gross sale": 175,
    "Comission": 35,
    "Gross minus comish": 140,
    "Net Profit $": 55.900000000000006,
    "Net Profit %": 0.6646848989298455
  },
  "Yeezy Beluga 2.0 size": {
    "Name of item": "Yeezy Beluga 2.0 size",
    "Color": "Grey",
    "Item Type": "Shoes",
    "Size": "8.5",
    "Brand": "Adidas",
    "My Cost": 240,
    "Gross sale": 375,
    "Comission": 0,
    "Gross minus comish": 375,
    "Net Profit $": 135,
    "Net Profit %": 0.5625
  },
  "Supreme Arm Sleeve NBA": {
    "Name of item": "Supreme Arm Sleeve NBA",
    "Color": "Red",
    "Item Type": "Accessory",
    "Size": "L/XL",
    "Brand": "Supreme",
    "My Cost": 52,
    "Gross sale": 150,
    "Comission": 30,
    "Gross minus comish": 120,
    "Net Profit $": 68,
    "Net Profit %": 1.3076923076923077
  },
  "Supreme wool camp cap": {
    "Name of item": "Supreme wool camp cap",
    "Color": "Red",
    "Item Type": "Hat",
    "Size": "OS",
    "Brand": "Supreme",
    "My Cost": 69,
    "Gross sale": 150,
    "Comission": 30,
    "Gross minus comish": 120,
    "Net Profit $": 51,
    "Net Profit %": 0.7391304347826086
  },
  "P-3D T-SHIRT BLACK": {
    "Name of item": "P-3D T-SHIRT BLACK",
    "Color": "Black",
    "Item Type": "T Shirt",
    "Size": "M",
    "Brand": "Palace",
    "My Cost": 51,
    "Gross sale": 130,
    "Comission": 26,
    "Gross minus comish": 104,
    "Net Profit $": 53,
    "Net Profit %": 1.0392156862745099
  },
  "P-3D T-SHIRT BLUE": {
    "Name of item": "P-3D T-SHIRT BLUE",
    "Color": "Blue",
    "Item Type": "T Shirt",
    "Size": "XL",
    "Brand": "Palace",
    "My Cost": 51,
    "Gross sale": 120,
    "Comission": 24,
    "Gross minus comish": 96,
    "Net Profit $": 45,
    "Net Profit %": 0.8823529411764706
  },
  "P-3D T-SHIRT TEAL BLUE": {
    "Name of item": "P-3D T-SHIRT TEAL BLUE",
    "Color": "Blue",
    "Item Type": "T Shirt",
    "Size": "XL",
    "Brand": "Palace",
    "My Cost": 51,
    "Gross sale": 120,
    "Comission": 24,
    "Gross minus comish": 96,
    "Net Profit $": 45,
    "Net Profit %": 0.8823529411764706
  },
  "TRI FERG PATCH BEANIE": {
    "Name of item": "TRI FERG PATCH BEANIE",
    "Color": "Grey",
    "Item Type": "Beanie",
    "Size": "OS",
    "Brand": "Palace",
    "My Cost": 35,
    "Gross sale": 65,
    "Comission": 0,
    "Gross minus comish": 65,
    "Net Profit $": 30,
    "Net Profit %": 0.8571428571428571
  },
  "Box Logo Beanie": {
    "Name of item": "Box Logo Beanie",
    "Color": "Grey",
    "Item Type": "Beanie",
    "Size": "OS",
    "Brand": "Supreme",
    "My Cost": 45,
    "Gross sale": 100,
    "Comission": 0,
    "Gross minus comish": 100,
    "Net Profit $": 55,
    "Net Profit %": 1.2222222222222223
  },
  "Gonz Tee Mustard ": {
    "Name of item": "Gonz Tee Mustard ",
    "Color": "Orange",
    "Item Type": "T Shirt",
    "Size": "XL",
    "Brand": "Supreme",
    "My Cost": 40.6,
    "Gross sale": 100,
    "Comission": 20,
    "Gross minus comish": 80,
    "Net Profit $": 39.4,
    "Net Profit %": 0.9704433497536945
  },
  "Arabic Logo L/S": {
    "Name of item": "Arabic Logo L/S",
    "Color": "Orange",
    "Item Type": "Long Sleeve Shirt",
    "Size": "L",
    "Brand": "Supreme",
    "My Cost": 51.5,
    "Gross sale": 140,
    "Comission": 28,
    "Gross minus comish": 112,
    "Net Profit $": 60.5,
    "Net Profit %": 1.174757281553398
  },
  "Yeezy Blue Tint Size 13": {
    "Name of item": "Yeezy Blue Tint Size 13",
    "Color": "Grey",
    "Item Type": "Shoes",
    "Size": "13",
    "Brand": "Adidas",
    "My Cost": 240,
    "Gross sale": 300,
    "Comission": 0,
    "Gross minus comish": 300,
    "Net Profit $": 60,
    "Net Profit %": 0.25
  },
  "Yeezy Blue Tint Size 9": {
    "Name of item": "Yeezy Blue Tint Size 9",
    "Color": "Grey",
    "Item Type": "Shoes",
    "Size": "9",
    "Brand": "Adidas",
    "My Cost": 240,
    "Gross sale": 530,
    "Comission": 106,
    "Gross minus comish": 424,
    "Net Profit $": 184,
    "Net Profit %": 0.7666666666666667
  },
  "BASICALLY A BEANIE ": {
    "Name of item": "BASICALLY A BEANIE ",
    "Color": "Blue",
    "Item Type": "Beanie",
    "Size": "OS",
    "Brand": "Palace",
    "My Cost": 38,
    "Gross sale": 65,
    "Comission": 13,
    "Gross minus comish": 52,
    "Net Profit $": 14,
    "Net Profit %": 0.3684210526315789
  },
  "P 6-PANEL BLACK": {
    "Name of item": "P 6-PANEL BLACK",
    "Color": "Black",
    "Item Type": "Hat",
    "Size": "OS",
    "Brand": "Palace",
    "My Cost": 54,
    "Gross sale": 120,
    "Comission": 24,
    "Gross minus comish": 96,
    "Net Profit $": 42,
    "Net Profit %": 0.7777777777777778
  },
  "SURKIT T-SHIRT": {
    "Name of item": "SURKIT T-SHIRT",
    "Color": "Grey",
    "Item Type": "T Shirt",
    "Size": "M",
    "Brand": "Palace",
    "My Cost": 60,
    "Gross sale": 125,
    "Comission": 25,
    "Gross minus comish": 100,
    "Net Profit $": 40,
    "Net Profit %": 0.6666666666666666
  },
  "Jellyfish Tee": {
    "Name of item": "Jellyfish Tee",
    "Color": "Peach",
    "Item Type": "T Shirt",
    "Size": "M",
    "Brand": "Supreme",
    "My Cost": 50,
    "Gross sale": 100,
    "Comission": 20,
    "Gross minus comish": 80,
    "Net Profit $": 30,
    "Net Profit %": 0.6
  },
  "Military Camp Cap Camo": {
    "Name of item": "Military Camp Cap Camo",
    "Color": "Camo",
    "Item Type": "T Shirt",
    "Size": "OS",
    "Brand": "Supreme",
    "My Cost": 52,
    "Gross sale": 120,
    "Comission": 24,
    "Gross minus comish": 96,
    "Net Profit $": 44,
    "Net Profit %": 0.8461538461538461
  },
  "Necklace Tee": {
    "Name of item": "Necklace Tee",
    "Color": "Peach",
    "Item Type": "T Shirt",
    "Size": "M",
    "Brand": "Supreme",
    "My Cost": 43,
    "Gross sale": 100,
    "Comission": 20,
    "Gross minus comish": 80,
    "Net Profit $": 37,
    "Net Profit %": 0.8604651162790697
  },
  "FTW Tee": {
    "Name of item": "FTW Tee",
    "Color": "Blue",
    "Item Type": "T Shirt",
    "Size": "M",
    "Brand": "Supreme",
    "My Cost": 47,
    "Gross sale": 80,
    "Comission": 0,
    "Gross minus comish": 80,
    "Net Profit $": 33,
    "Net Profit %": 0.7021276595744681
  },
  "Felt S Logo 6-Panel": {
    "Name of item": "Felt S Logo 6-Panel",
    "Color": "Yellow",
    "Item Type": "Hat",
    "Size": "OS",
    "Brand": "Supreme",
    "My Cost": 58,
    "Gross sale": 110,
    "Comission": 22,
    "Gross minus comish": 88,
    "Net Profit $": 30,
    "Net Profit %": 0.5172413793103449
  },
  "Shoulder Bag black": {
    "Name of item": "Shoulder Bag black",
    "Color": "Black",
    "Item Type": "Accessory",
    "Size": "OS",
    "Brand": "Supreme",
    "My Cost": 64,
    "Gross sale": 120,
    "Comission": 0,
    "Gross minus comish": 120,
    "Net Profit $": 56,
    "Net Profit %": 0.875
  },
  "Grip Work Gloves": {
    "Name of item": "Grip Work Gloves",
    "Color": "Red",
    "Item Type": "Accessory",
    "Size": "N/A",
    "Brand": "Supreme",
    "My Cost": 15.5,
    "Gross sale": 20,
    "Comission": 0,
    "Gross minus comish": 20,
    "Net Profit $": 4.5,
    "Net Profit %": 0.2903225806451613
  },
  "Molotov Tee": {
    "Name of item": "Molotov Tee",
    "Color": "Black",
    "Item Type": "T Shirt",
    "Size": "M",
    "Brand": "Supreme",
    "My Cost": 41.5,
    "Gross sale": 50,
    "Comission": 0,
    "Gross minus comish": 50,
    "Net Profit $": 8.5,
    "Net Profit %": 0.20481927710843373
  },
  "Chair Tee": {
    "Name of item": "Chair Tee",
    "Color": "Red",
    "Item Type": "T Shirt",
    "Size": "M",
    "Brand": "Supreme",
    "My Cost": 41.5,
    "Gross sale": 60,
    "Comission": 0,
    "Gross minus comish": 60,
    "Net Profit $": 18.5,
    "Net Profit %": 0.4457831325301205
  },
  "Waist Bag black": {
    "Name of item": "Waist Bag black",
    "Color": "Black",
    "Item Type": "Accessory",
    "Size": "OS",
    "Brand": "Supreme",
    "My Cost": 98,
    "Gross sale": 130,
    "Comission": 0,
    "Gross minus comish": 130,
    "Net Profit $": 32,
    "Net Profit %": 0.32653061224489793
  },
  "Yeezy 700 Waverunner": {
    "Name of item": "Yeezy 700 Waverunner",
    "Color": "Grey",
    "Item Type": "Shoes",
    "Size": "12",
    "Brand": "Adidas",
    "My Cost": 342,
    "Gross sale": 400,
    "Comission": 0,
    "Gross minus comish": 400,
    "Net Profit $": 58,
    "Net Profit %": 0.1695906432748538
  },
  "Yeezy 500 Blush": {
    "Name of item": "Yeezy 500 Blush",
    "Color": "Grey",
    "Item Type": "Shoes",
    "Size": "9.5",
    "Brand": "Adidas",
    "My Cost": 240,
    "Gross sale": 400,
    "Comission": 60,
    "Gross minus comish": 340,
    "Net Profit $": 100,
    "Net Profit %": 0.4166666666666667
  },
  "Palace Hoodie Sirkit M navy": {
    "Name of item": "Palace Hoodie Sirkit M navy",
    "Color": "Navy",
    "Item Type": "Sweatshirt",
    "Size": "M",
    "Brand": "Palace",
    "My Cost": 154,
    "Gross sale": 300,
    "Comission": 60,
    "Gross minus comish": 240,
    "Net Profit $": 86,
    "Net Profit %": 0.5584415584415584
  },
  "Palace Hoodie Sirkit ": {
    "Name of item": "Palace Hoodie Sirkit ",
    "Color": "Black",
    "Item Type": "Sweatshirt",
    "Size": "L",
    "Brand": "Palace",
    "My Cost": 154,
    "Gross sale": 300,
    "Comission": 60,
    "Gross minus comish": 240,
    "Net Profit $": 86,
    "Net Profit %": 0.5584415584415584
  },
  "Public Enemy Tee": {
    "Name of item": "Public Enemy Tee",
    "Color": "Red",
    "Item Type": "T Shirt",
    "Size": "M",
    "Brand": "Supreme",
    "My Cost": 57.5,
    "Gross sale": 100,
    "Comission": 20,
    "Gross minus comish": 80,
    "Net Profit $": 22.5,
    "Net Profit %": 0.391304347826087
  },
  "Public Enemy Terrordome Tee": {
    "Name of item": "Public Enemy Terrordome Tee",
    "Color": "Red",
    "Item Type": "T Shirt",
    "Size": "M",
    "Brand": "Supreme",
    "My Cost": 57.5,
    "Gross sale": 100,
    "Comission": 20,
    "Gross minus comish": 80,
    "Net Profit $": 22.5,
    "Net Profit %": 0.391304347826087
  },
  "Palace Hoodie Jumbo L": {
    "Name of item": "Palace Hoodie Jumbo L",
    "Color": "Black",
    "Item Type": "Sweatshirt",
    "Size": "L",
    "Brand": "Palace",
    "My Cost": 160,
    "Gross sale": 300,
    "Comission": 60,
    "Gross minus comish": 240,
    "Net Profit $": 80,
    "Net Profit %": 0.5
  },
  "Supreme Diamond Tee M": {
    "Name of item": "Supreme Diamond Tee M",
    "Color": "Purple",
    "Item Type": "T Shirt",
    "Size": "M",
    "Brand": "Supreme",
    "My Cost": 56,
    "Gross sale": 100,
    "Comission": 20,
    "Gross minus comish": 80,
    "Net Profit $": 24,
    "Net Profit %": 0.42857142857142855
  },
  "Supreme®/The North Face® Metallic Shoulder Bag": {
    "Name of item": "Supreme®/The North Face® Metallic Shoulder Bag",
    "Color": "Gold",
    "Item Type": "Accessory",
    "Size": "OS",
    "Brand": "Supreme",
    "My Cost": 75.23,
    "Gross sale": 160,
    "Comission": 32,
    "Gross minus comish": 128,
    "Net Profit $": 52.769999999999996,
    "Net Profit %": 0.7014488900704505
  },
  "Supreme®/The North Face® Metallic Borealis Backpack": {
    "Name of item": "Supreme®/The North Face® Metallic Borealis Backpack",
    "Color": "Grey",
    "Item Type": "Accessory",
    "Size": "OS",
    "Brand": "Supreme",
    "My Cost": 172.22,
    "Gross sale": 350,
    "Comission": 70,
    "Gross minus comish": 280,
    "Net Profit $": 107.78,
    "Net Profit %": 0.6258274300313552
  },
  "Adidas UNDFD White Ultraboost": {
    "Name of item": "Adidas UNDFD White Ultraboost",
    "Color": "Black",
    "Item Type": "Shoes",
    "Size": "12",
    "Brand": "Undefeated ",
    "My Cost": 235,
    "Gross sale": 350,
    "Comission": 70,
    "Gross minus comish": 280,
    "Net Profit $": 45,
    "Net Profit %": 0.19148936170212766
  },
  "Embossed Logo Hooded Sweatshirt": {
    "Name of item": "Embossed Logo Hooded Sweatshirt",
    "Color": "Red",
    "Item Type": "Sweatshirt",
    "Size": "M",
    "Brand": "Supreme",
    "My Cost": 180,
    "Gross sale": 350,
    "Comission": 70,
    "Gross minus comish": 280,
    "Net Profit $": 100,
    "Net Profit %": 0.5555555555555556
  },
  "Reflective Tab Pocket Camp Cap": {
    "Name of item": "Reflective Tab Pocket Camp Cap",
    "Color": "Red",
    "Item Type": "Hat",
    "Size": "OS",
    "Brand": "Supreme",
    "My Cost": 60,
    "Gross sale": 110,
    "Comission": 22,
    "Gross minus comish": 88,
    "Net Profit $": 28,
    "Net Profit %": 0.4666666666666667
  },
  "Sleeve Embroidery Hooded Sweatshirt": {
    "Name of item": "Sleeve Embroidery Hooded Sweatshirt",
    "Color": "Red",
    "Item Type": "Sweatshirt",
    "Size": "M",
    "Brand": "Supreme",
    "My Cost": 180,
    "Gross sale": 350,
    "Comission": 70,
    "Gross minus comish": 280,
    "Net Profit $": 100,
    "Net Profit %": 0.5555555555555556
  },
  "Leg Embroidery Sweatshort": {
    "Name of item": "Leg Embroidery Sweatshort",
    "Color": "Red",
    "Item Type": "Shorts",
    "Size": "M",
    "Brand": "Supreme",
    "My Cost": 133,
    "Gross sale": 275,
    "Comission": 55,
    "Gross minus comish": 220,
    "Net Profit $": 87,
    "Net Profit %": 0.6541353383458647
  },
  "Jar Set (Set of 2)": {
    "Name of item": "Jar Set (Set of 2)",
    "Color": "Clear",
    "Item Type": "Accessory",
    "Size": "N/A",
    "Brand": "Supreme",
    "My Cost": 42,
    "Gross sale": 90,
    "Comission": 0,
    "Gross minus comish": 90,
    "Net Profit $": 48,
    "Net Profit %": 1.1428571428571428
  },
  "Palazzo LS": {
    "Name of item": "Palazzo LS",
    "Color": "Black",
    "Item Type": "Long Sleeve Shirt",
    "Size": "M",
    "Brand": "Palace",
    "My Cost": 64,
    "Gross sale": 115,
    "Comission": 23,
    "Gross minus comish": 92,
    "Net Profit $": 28,
    "Net Profit %": 0.4375
  },
  "P cap Aqua ": {
    "Name of item": "P cap Aqua ",
    "Color": "Blue",
    "Item Type": "Hat",
    "Size": "OS",
    "Brand": "Palace",
    "My Cost": 54,
    "Gross sale": 110,
    "Comission": 22,
    "Gross minus comish": 88,
    "Net Profit $": 34,
    "Net Profit %": 0.6296296296296297
  },
  "Shoulder Bag red": {
    "Name of item": "Shoulder Bag red",
    "Color": "Red",
    "Item Type": "Accessory",
    "Size": "OS",
    "Brand": "Supreme",
    "My Cost": 65,
    "Gross sale": 130,
    "Comission": 0,
    "Gross minus comish": 130,
    "Net Profit $": 65,
    "Net Profit %": 1
  },
  "Waist Bag Red": {
    "Name of item": "Waist Bag Red",
    "Color": "Red",
    "Item Type": "Accessory",
    "Size": "OS",
    "Brand": "Supreme",
    "My Cost": 101,
    "Gross sale": 200,
    "Comission": 40,
    "Gross minus comish": 160,
    "Net Profit $": 59,
    "Net Profit %": 0.5841584158415841
  },
  "FlatSack Camo": {
    "Name of item": "FlatSack Camo",
    "Color": "Camo",
    "Item Type": "Accessory",
    "Size": "OS",
    "Brand": "Palace",
    "My Cost": 80,
    "Gross sale": 150,
    "Comission": 30,
    "Gross minus comish": 120,
    "Net Profit $": 40,
    "Net Profit %": 0.5
  },
  "Snakeskin BackPack TNF": {
    "Name of item": "Snakeskin BackPack TNF",
    "Color": "Camo",
    "Item Type": "Accessory",
    "Size": "OS",
    "Brand": "Supreme",
    "My Cost": 150,
    "Gross sale": 200,
    "Comission": 40,
    "Gross minus comish": 160,
    "Net Profit $": 10,
    "Net Profit %": 0.06666666666666667
  },
  "SIGG™ Traveller 0.6L Water Bottle": {
    "Name of item": "SIGG™ Traveller 0.6L Water Bottle",
    "Color": "Red",
    "Item Type": "Accessory",
    "Size": "OS",
    "Brand": "Supreme",
    "My Cost": 45.5,
    "Gross sale": 100,
    "Comission": 20,
    "Gross minus comish": 80,
    "Net Profit $": 34.5,
    "Net Profit %": 0.7582417582417582
  },
  "SealLine See Pouch Small Red": {
    "Name of item": "SealLine See Pouch Small Red",
    "Color": "Red",
    "Item Type": "Accessory",
    "Size": "S",
    "Brand": "Supreme",
    "My Cost": 31.5,
    "Gross sale": 60,
    "Comission": 12,
    "Gross minus comish": 48,
    "Net Profit $": 16.5,
    "Net Profit %": 0.5238095238095238
  },
  "Logo Zippo Red": {
    "Name of item": "Logo Zippo Red",
    "Color": "Red",
    "Item Type": "Accessory",
    "Size": "OS",
    "Brand": "Supreme",
    "My Cost": 58,
    "Gross sale": 150,
    "Comission": 30,
    "Gross minus comish": 120,
    "Net Profit $": 62,
    "Net Profit %": 1.0689655172413792
  },
  "Suede P Cap Red": {
    "Name of item": "Suede P Cap Red",
    "Color": "Red",
    "Item Type": "Hat",
    "Size": "OS",
    "Brand": "Palace",
    "My Cost": 60,
    "Gross sale": 125,
    "Comission": 25,
    "Gross minus comish": 100,
    "Net Profit $": 40,
    "Net Profit %": 0.6666666666666666
  },
  "Suede P Cap Black": {
    "Name of item": "Suede P Cap Black",
    "Color": "Black",
    "Item Type": "Hat",
    "Size": "OS",
    "Brand": "Palace",
    "My Cost": 60,
    "Gross sale": 125,
    "Comission": 25,
    "Gross minus comish": 100,
    "Net Profit $": 40,
    "Net Profit %": 0.6666666666666666
  },
  "Suede P Cap Brown": {
    "Name of item": "Suede P Cap Brown",
    "Color": "Brown",
    "Item Type": "Hat",
    "Size": "OS",
    "Brand": "Palace",
    "My Cost": 60,
    "Gross sale": 125,
    "Comission": 25,
    "Gross minus comish": 100,
    "Net Profit $": 40,
    "Net Profit %": 0.6666666666666666
  },
  "StatGear Pocket Samurai Knife Red": {
    "Name of item": "StatGear Pocket Samurai Knife Red",
    "Color": "Red",
    "Item Type": "Accessory",
    "Size": "N/A",
    "Brand": "Supreme",
    "My Cost": 50,
    "Gross sale": 70,
    "Comission": 0,
    "Gross minus comish": 70,
    "Net Profit $": 20,
    "Net Profit %": 0.4
  },
  "Tentacles Tee ": {
    "Name of item": "Tentacles Tee ",
    "Color": "Blue",
    "Item Type": "T Shirt",
    "Size": "M",
    "Brand": "Supreme",
    "My Cost": 43,
    "Gross sale": 100,
    "Comission": 20,
    "Gross minus comish": 80,
    "Net Profit $": 37,
    "Net Profit %": 0.8604651162790697
  },
  "Gonz Logo Tee": {
    "Name of item": "Gonz Logo Tee",
    "Color": "Orange",
    "Item Type": "T Shirt",
    "Size": "M",
    "Brand": "Supreme",
    "My Cost": 48,
    "Gross sale": 90,
    "Comission": 0,
    "Gross minus comish": 90,
    "Net Profit $": 42,
    "Net Profit %": 0.875
  },
  "Swimmers Tee ": {
    "Name of item": "Swimmers Tee ",
    "Color": "Dark Grey",
    "Item Type": "T Shirt",
    "Size": "M",
    "Brand": "Supreme",
    "My Cost": 43,
    "Gross sale": 100,
    "Comission": 0,
    "Gross minus comish": 100,
    "Net Profit $": 57,
    "Net Profit %": 1.3255813953488371
  },
  "Gonz Logo Tee ": {
    "Name of item": "Gonz Logo Tee ",
    "Color": "Orange",
    "Item Type": "T Shirt",
    "Size": "M",
    "Brand": "Supreme",
    "My Cost": 48,
    "Gross sale": 100,
    "Comission": 20,
    "Gross minus comish": 80,
    "Net Profit $": 32,
    "Net Profit %": 0.6666666666666666
  },
  "BACtrack® Go Keychain": {
    "Name of item": "BACtrack® Go Keychain",
    "Color": "White",
    "Item Type": "Accessory",
    "Size": "N/A",
    "Brand": "Supreme",
    "My Cost": 55,
    "Gross sale": 65,
    "Comission": 0,
    "Gross minus comish": 65,
    "Net Profit $": 10,
    "Net Profit %": 0.18181818181818182
  },
  "P Cap Grey": {
    "Name of item": "P Cap Grey",
    "Color": "Grey",
    "Item Type": "Hat",
    "Size": "OS",
    "Brand": "Palace",
    "My Cost": 54,
    "Gross sale": 115,
    "Comission": 23,
    "Gross minus comish": 92,
    "Net Profit $": 38,
    "Net Profit %": 0.7037037037037037
  },
  "P Cap Blue": {
    "Name of item": "P Cap Blue",
    "Color": "Blue",
    "Item Type": "Hat",
    "Size": "OS",
    "Brand": "Palace",
    "My Cost": 54,
    "Gross sale": 115,
    "Comission": 23,
    "Gross minus comish": 92,
    "Net Profit $": 38,
    "Net Profit %": 0.7037037037037037
  },
  "Washed Chino Twill Camp Cap": {
    "Name of item": "Washed Chino Twill Camp Cap",
    "Color": "Red",
    "Item Type": "Hat",
    "Size": "OS",
    "Brand": "Supreme",
    "My Cost": 64.16,
    "Gross sale": 120,
    "Comission": 24,
    "Gross minus comish": 96,
    "Net Profit $": 31.840000000000003,
    "Net Profit %": 0.4962593516209477
  },
  "Reflective Camo Camp Cap": {
    "Name of item": "Reflective Camo Camp Cap",
    "Color": "Blue",
    "Item Type": "Hat",
    "Size": "OS",
    "Brand": "Supreme",
    "My Cost": 63.22,
    "Gross sale": 110,
    "Comission": 22,
    "Gross minus comish": 88,
    "Net Profit $": 24.78,
    "Net Profit %": 0.3919645681746283
  },
  "Shoulder Bag Purple": {
    "Name of item": "Shoulder Bag Purple",
    "Color": "Purple",
    "Item Type": "Accessory",
    "Size": "OS",
    "Brand": "Supreme",
    "My Cost": 77.75,
    "Gross sale": 175,
    "Comission": 35,
    "Gross minus comish": 140,
    "Net Profit $": 62.25,
    "Net Profit %": 0.8006430868167203
  },
  "Waist Bag Black": {
    "Name of item": "Waist Bag Black",
    "Color": "Black",
    "Item Type": "Accessory",
    "Size": "OS",
    "Brand": "Supreme",
    "My Cost": 98.42,
    "Gross sale": 175,
    "Comission": 35,
    "Gross minus comish": 140,
    "Net Profit $": 41.58,
    "Net Profit %": 0.422475106685633
  },
  "1994 LS ": {
    "Name of item": "1994 LS ",
    "Color": "Black",
    "Item Type": "Long Sleeve Shirt",
    "Size": "M",
    "Brand": "Supreme",
    "My Cost": 47.13,
    "Gross sale": 100,
    "Comission": 20,
    "Gross minus comish": 80,
    "Net Profit $": 32.87,
    "Net Profit %": 0.697432633142372
  },
  "1994 LS": {
    "Name of item": "1994 LS",
    "Color": "Dark green",
    "Item Type": "Long Sleeve Shirt",
    "Size": "L",
    "Brand": "Supreme",
    "My Cost": 46.22,
    "Gross sale": 100,
    "Comission": 20,
    "Gross minus comish": 80,
    "Net Profit $": 33.78,
    "Net Profit %": 0.7308524448290784
  },
  "Bottle Cap Tee": {
    "Name of item": "Bottle Cap Tee",
    "Color": "Blue",
    "Item Type": "T Shirt",
    "Size": "L",
    "Brand": "Supreme",
    "My Cost": 41.87,
    "Gross sale": 100,
    "Comission": 20,
    "Gross minus comish": 80,
    "Net Profit $": 38.13,
    "Net Profit %": 0.9106759016001912
  },
  "Liquid Tee": {
    "Name of item": "Liquid Tee",
    "Color": "Brown",
    "Item Type": "T Shirt",
    "Size": "L",
    "Brand": "Supreme",
    "My Cost": 41.87,
    "Gross sale": 100,
    "Comission": 20,
    "Gross minus comish": 80,
    "Net Profit $": 38.13,
    "Net Profit %": 0.9106759016001912
  },
  "Still Life Tee": {
    "Name of item": "Still Life Tee",
    "Color": "Red",
    "Item Type": "T Shirt",
    "Size": "L",
    "Brand": "Supreme",
    "My Cost": 41.87,
    "Gross sale": 100,
    "Comission": 20,
    "Gross minus comish": 80,
    "Net Profit $": 38.13,
    "Net Profit %": 0.9106759016001912
  },
  "Backpack - Black": {
    "Name of item": "Backpack - Black",
    "Color": "Black",
    "Item Type": "Accessory",
    "Size": "OS",
    "Brand": "Supreme",
    "My Cost": 183,
    "Gross sale": 300,
    "Comission": 60,
    "Gross minus comish": 240,
    "Net Profit $": 57,
    "Net Profit %": 0.3114754098360656
  },
  "Group tee": {
    "Name of item": "Group tee",
    "Color": "Black",
    "Item Type": "T Shirt",
    "Size": "M",
    "Brand": "Supreme",
    "My Cost": 50,
    "Gross sale": 100,
    "Comission": 20,
    "Gross minus comish": 80,
    "Net Profit $": 30,
    "Net Profit %": 0.6
  },
  "Eternal tee": {
    "Name of item": "Eternal tee",
    "Color": "Black",
    "Item Type": "T Shirt",
    "Size": "M",
    "Brand": "Supreme",
    "My Cost": 45,
    "Gross sale": 115,
    "Comission": 23,
    "Gross minus comish": 92,
    "Net Profit $": 47,
    "Net Profit %": 1.0444444444444445
  },
  "Faces tee ": {
    "Name of item": "Faces tee ",
    "Color": "White",
    "Item Type": "T Shirt",
    "Size": "M",
    "Brand": "Supreme",
    "My Cost": 45,
    "Gross sale": 100,
    "Comission": 20,
    "Gross minus comish": 80,
    "Net Profit $": 35,
    "Net Profit %": 0.7777777777777778
  },
  "Cat in the Hat Hoodie": {
    "Name of item": "Cat in the Hat Hoodie",
    "Color": "Blue",
    "Item Type": "Sweatshirt",
    "Size": "L",
    "Brand": "Supreme",
    "My Cost": 195,
    "Gross sale": 400,
    "Comission": 80,
    "Gross minus comish": 320,
    "Net Profit $": 125,
    "Net Profit %": 0.6410256410256411
  },
  "PalBoy tshirt ": {
    "Name of item": "PalBoy tshirt ",
    "Color": "Red",
    "Item Type": "T Shirt",
    "Size": "L",
    "Brand": "Palace",
    "My Cost": 60,
    "Gross sale": 115,
    "Comission": 23,
    "Gross minus comish": 92,
    "Net Profit $": 32,
    "Net Profit %": 0.5333333333333333
  },
  "Leopard head band": {
    "Name of item": "Leopard head band",
    "Color": "Leaopard",
    "Item Type": "Accessory",
    "Size": "OS",
    "Brand": "Supreme",
    "My Cost": 45,
    "Gross sale": 120,
    "Comission": 24,
    "Gross minus comish": 96,
    "Net Profit $": 51,
    "Net Profit %": 1.1333333333333333
  },
  "P 6-panel Black Shell": {
    "Name of item": "P 6-panel Black Shell",
    "Color": "Black",
    "Item Type": "Hat",
    "Size": "OS",
    "Brand": "Palace",
    "My Cost": 52,
    "Gross sale": 110,
    "Comission": 22,
    "Gross minus comish": 88,
    "Net Profit $": 36,
    "Net Profit %": 0.6923076923076923
  },
  "Triferg Patch Beanie": {
    "Name of item": "Triferg Patch Beanie",
    "Color": "Black",
    "Item Type": "Beanie",
    "Size": "OS",
    "Brand": "Palace",
    "My Cost": 42,
    "Gross sale": 80,
    "Comission": 16,
    "Gross minus comish": 64,
    "Net Profit $": 22,
    "Net Profit %": 0.5238095238095238
  },
  "Supreme wool camp cap herringbone": {
    "Name of item": "Supreme wool camp cap herringbone",
    "Color": "Black",
    "Item Type": "Hat",
    "Size": "OS",
    "Brand": "Supreme",
    "My Cost": 62.5,
    "Gross sale": 125,
    "Comission": 25,
    "Gross minus comish": 100,
    "Net Profit $": 37.5,
    "Net Profit %": 0.6
  },
  "Chris Cunningham Chihuahua Tee": {
    "Name of item": "Chris Cunningham Chihuahua Tee",
    "Color": "Dark Grey",
    "Item Type": "T Shirt",
    "Size": "M",
    "Brand": "Supreme",
    "My Cost": 51.5,
    "Gross sale": 90,
    "Comission": 18,
    "Gross minus comish": 72,
    "Net Profit $": 20.5,
    "Net Profit %": 0.39805825242718446
  },
  "Magnetic Kickstand Light ": {
    "Name of item": "Magnetic Kickstand Light ",
    "Color": "Red",
    "Item Type": "Accessory",
    "Size": "N/A",
    "Brand": "Supreme",
    "My Cost": 32,
    "Gross sale": 60,
    "Comission": 12,
    "Gross minus comish": 48,
    "Net Profit $": 16,
    "Net Profit %": 0.5
  },
  "Octo Triferg ": {
    "Name of item": "Octo Triferg ",
    "Color": "White",
    "Item Type": "T Shirt",
    "Size": "L",
    "Brand": "Palace",
    "My Cost": 54,
    "Gross sale": 110,
    "Comission": 22,
    "Gross minus comish": 88,
    "Net Profit $": 34,
    "Net Profit %": 0.6296296296296297
  },
  "North Face Photo Sweatshirt": {
    "Name of item": "North Face Photo Sweatshirt",
    "Color": "Black",
    "Item Type": "Sweatshirt",
    "Size": "L",
    "Brand": "Supreme",
    "My Cost": 150,
    "Gross sale": 300,
    "Comission": 60,
    "Gross minus comish": 240,
    "Net Profit $": 90,
    "Net Profit %": 0.6
  },
  "North Face Fold Beanie": {
    "Name of item": "North Face Fold Beanie",
    "Color": "Black",
    "Item Type": "Beanie",
    "Size": "OS",
    "Brand": "Supreme",
    "My Cost": 50,
    "Gross sale": 100,
    "Comission": 20,
    "Gross minus comish": 80,
    "Net Profit $": 30,
    "Net Profit %": 0.6
  },
  "North Face Photo Tee ": {
    "Name of item": "North Face Photo Tee ",
    "Color": "Black ",
    "Item Type": "T Shirt",
    "Size": "L",
    "Brand": "Supreme",
    "My Cost": 62,
    "Gross sale": 115,
    "Comission": 23,
    "Gross minus comish": 92,
    "Net Profit $": 30,
    "Net Profit %": 0.4838709677419355
  }
}